MAINCLASS=Genome
include ../common/Makefile.flags

SRC=${MAINCLASS}.java \
	../common/Random.java \
	Bitmap.java \
	Gene.java \
	Segments.java \
	endInfoEntry.java \
	constructEntry.java \
	../../../ClassLibrary/JavaSTM/Barrier.java \
	Sequencer.java \
	Table.java \
	Hashtable.java

include ../common/Makefile.builds

prep:

clean:
	rm -rf tmpbuilddirectory
	rm *.bin
